import { NextRequest, NextResponse } from 'next/server';
import jwt from 'jsonwebtoken';
import { connectToDatabase, queryOneAsync, aggregate, ObjectId } from '@/lib/db';
import { getPlanCapabilities, resolvePlanShape } from '@/lib/subscription';

const JWT_SECRET = process.env.JWT_SECRET || 'your-super-secret-jwt-key-change-in-production';
// Intentionally empty: insights are generated by deterministic business rules, not an external provider.
const AI_PROVIDER_API_KEY = '';
export const dynamic = 'force-dynamic';

function getUserFromRequest(request: NextRequest) {
  const token = request.cookies.get('token')?.value;
  if (!token) return null;
  
  try {
    const payload = jwt.verify(token, JWT_SECRET) as { userId: string; role: string };
    return payload;
  } catch {
    return null;
  }
}

async function resolvePlanByIdentifier(identifier: string | undefined) {
  if (!identifier) return null;

  let plan = await queryOneAsync('subscriptionPlans', { _id: identifier });
  if (!plan && ObjectId.isValid(identifier)) {
    plan = await queryOneAsync('subscriptionPlans', { _id: new ObjectId(identifier) });
  }
  if (!plan) {
    plan = await queryOneAsync('subscriptionPlans', { name: identifier });
  }

  return plan;
}

export async function GET(request: NextRequest) {
  try {
    await connectToDatabase();
    
    const user = getUserFromRequest(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get user's business
    const business = await queryOneAsync('businesses', { userId: user.userId });
    if (!business) {
      return NextResponse.json({ error: 'Business not found' }, { status: 404 });
    }

    // Check user's subscription for AI features
    const subscription = await queryOneAsync('subscriptions', { userId: user.userId, status: 'active' });
    
    // Check if AI features are enabled
    let aiEnabled = false;
    if (subscription) {
      const plan = await resolvePlanByIdentifier(subscription.planId);
      const planShape = resolvePlanShape(plan);
      aiEnabled = getPlanCapabilities(planShape).aiInsightsEnabled;
    }

    if (!aiEnabled) {
      return NextResponse.json({ 
        error: 'AI insights require Business plan',
        upgradeRequired: true 
      }, { status: 403 });
    }

    const businessId = business._id;
    const now = new Date();
    const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const monthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

    // Get current week stats
    const currentWeekStats = await aggregate('sales', [
      { $match: { businessId, date: { $gte: weekAgo, $lte: now } } },
      { $group: { _id: null, total: { $sum: '$total' }, count: { $sum: 1 } } }
    ]);

    // Get previous week stats
    const prevWeekStart = new Date(weekAgo.getTime() - 7 * 24 * 60 * 60 * 1000);
    const prevWeekStats = await aggregate('sales', [
      { $match: { businessId, date: { $gte: prevWeekStart, $lte: weekAgo } } },
      { $group: { _id: null, total: { $sum: '$total' }, count: { $sum: 1 } } }
    ]);

    // Get monthly stats
    const monthlyStats = await aggregate('sales', [
      { $match: { businessId, date: { $gte: monthAgo, $lte: now } } },
      { $group: { _id: null, total: { $sum: '$total' }, count: { $sum: 1 } } }
    ]);

    // Get top products
    const topProducts = await aggregate('sales', [
      { $match: { businessId, date: { $gte: monthAgo, $lte: now } } },
      { $lookup: { from: 'products', localField: 'productId', foreignField: '_id', as: 'product' } },
      { $unwind: '$product' },
      { $group: { _id: '$productId', name: { $first: '$product.name' }, total: { $sum: '$total' } } },
      { $sort: { total: -1 } },
      { $limit: 5 }
    ]);

    // Calculate insights
    const currentWeekRevenue = currentWeekStats[0]?.total || 0;
    const prevWeekRevenue = prevWeekStats[0]?.total || 0;
    const weeklyGrowth = prevWeekRevenue > 0 
      ? ((currentWeekRevenue - prevWeekRevenue) / prevWeekRevenue) * 100 
      : 0;

    const monthlyRevenue = monthlyStats[0]?.total || 0;
    const monthlySales = monthlyStats[0]?.count || 0;
    const averageOrderValue = monthlySales > 0 ? monthlyRevenue / monthlySales : 0;

    // Generate insights
    const insights: any[] = [];

    // Sales trend insight
    if (weeklyGrowth < -10) {
      insights.push({
        type: 'warning',
        title: 'Sales Decline Detected',
        message: `Your sales dropped by ${Math.abs(weeklyGrowth).toFixed(1)}% this week compared to last week. Consider reviewing your pricing or promotions.`,
        action: 'Review Sales Strategy'
      });
    } else if (weeklyGrowth > 10) {
      insights.push({
        type: 'success',
        title: 'Strong Week',
        message: `Great job! Your sales increased by ${weeklyGrowth.toFixed(1)}% this week compared to last week.`,
        action: null
      });
    }

    // Product insights
    if (topProducts.length > 0) {
      const topProduct = topProducts[0];
      insights.push({
        type: 'info',
        title: 'Top Performer',
        message: `"${topProduct.name}" is your best-selling product with $${topProduct.total.toFixed(2)} in monthly revenue.`,
        action: 'View Product'
      });
    }

    // Recommendations
    if (monthlySales > 0 && monthlyRevenue < 100) {
      insights.push({
        type: 'recommendation',
        title: 'Price Adjustment',
        message: 'Your average transaction is below $100. Consider offering bundles or upselling to increase revenue per customer.',
        action: 'View Analytics'
      });
    }

    if (averageOrderValue > 0 && averageOrderValue < 25) {
      insights.push({
        type: 'recommendation',
        title: 'Low Average Order Value',
        message: `Average order value is $${averageOrderValue.toFixed(2)}. Consider a tiered pricing strategy to move customers to higher-value purchases.`,
        action: 'Review Pricing'
      });
    }

    const performanceSummary =
      weeklyGrowth <= -10
        ? `Performance summary: revenue declined ${Math.abs(weeklyGrowth).toFixed(1)}% week-over-week. Prioritize promotions and pricing review.`
        : weeklyGrowth >= 10
          ? `Performance summary: revenue grew ${weeklyGrowth.toFixed(1)}% week-over-week with positive momentum.`
          : `Performance summary: revenue is stable week-over-week (${weeklyGrowth.toFixed(1)}%).`;

    // Calculate health score (simplified)
    const healthScore = Math.min(100, Math.max(0, 50 + weeklyGrowth * 2 + (monthlySales > 10 ? 20 : 0)));

    return NextResponse.json({
      insights,
      healthScore: Math.round(healthScore),
      provider: {
        mode: 'rules-based',
        apiKeyConfigured: AI_PROVIDER_API_KEY.length > 0
      },
      summary: {
        weeklyRevenue: currentWeekRevenue,
        weeklyGrowth: weeklyGrowth.toFixed(1),
        monthlyRevenue,
        monthlySales,
        averageOrderValue,
        performanceSummary,
        topProducts: topProducts.map((p: any) => ({
          name: p.name,
          revenue: p.total
        }))
      }
    });
  } catch (error) {
    console.error('Error fetching AI insights:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
